### ISSUE TITLE
Input more than one zone/schedule

### ISSUE THREAD

**Issue by dchopson** [Argonne-National-Laboratory/ISOmodel#2]
This is more of a question than an issue: is it possible to define more than one zone/schedule in the ism input file?

**Comment by muehleisen** [comment]
Daniel,
It is a one-zone, one schedule model.  For the use cases that we envision (i.e. low fidelity where you need a really fast model) a single zone equivalent works fairly well.

**Comment by dchopson** [comment]
@muehleisen got it, thanks for the feedback
